# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7af804d08881e5d731e5273ead8d649f0e61700ee5facaddd27bc7b8dc9e951f91ec059108cc73fcbaedec4d5683063651331ac1cdc2ce93a0aa2f556ceb52a0

test:
  secret_key_base: e772ccab522f89a19e3037d56be924e211a31c372fbfe5e79777eabc868071c3e9914079e4e8e92b6ef3a8fea0ca3b5e0fc98e516aa7d823d0ef96ce501e859d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
